name: Golden Tests

on:
  push:
    branches: [master]

jobs:
  golden_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Flutter
        uses: flutter-actions/setup-flutter@v3
        # (Optional) Specify Flutter version (e.g., with: flutter-version: 'stable')
        with:
          channel: stable
          version: 3.22.2

      - name: Install dependencies
        run: flutter pub get

      - name: Run golden tests
        run: flutter test --coverage