name: Golden Tests

on:
  push:
    branches: [master]

jobs:
  golden_tests:
    runs-on: macOS-latest
    #runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Flutter
        uses: flutter-actions/setup-flutter@v3
        # (Optional) Specify Flutter version (e.g., with: flutter-version: 'stable')
        with:
          channel: stable
          version: 3.22.2

      - name: Install dependencies
        run: flutter pub get

        ## start update goldens

      ## start ubuntu
#      - name: Install Git
#        run: |
#          sudo apt-get update
#          sudo apt-get install git
      ## end ubuntu
      ## start macOS
#      - name: Install Git
#        run: brew install git
      ## end macOS
      - name: Configure Git
        run: |
          git config --global user.name "Cristiano Cortez (Esteira)"
          git config --global user.email "cristianocortez@gmail.com"
      - name: Update golden tests and commit changes
        run: |
          flutter test --update-goldens
          git add .
          git commit -m "Update golden images"
          git push origin master

        ## end update goldens

      - name: Run golden tests
        run: flutter test --coverage